apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/alban34/random-legendary-llm
    newTag: dev-bce544943f4f2d8cfdc68aee06f21c9fb1184d74
