apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/alban34/random-legendary-llm
    newTag: dev-8a681d3d77cb6060a62852c17775698e2e17207a
