apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/alban34/random-legendary-llm
    newTag: dev-833253b3cf5605ed3a6529ecd678ec5ea028d832
