export const DEFAULT_LOCALE_ID = 'en-US';

const SELECTABLE_LOCALES = [
  { id: 'en-US', label: 'English', nativeLabel: 'English' },
  { id: 'fr-FR', label: 'French', nativeLabel: 'Français' },
  { id: 'de-DE', label: 'German', nativeLabel: 'Deutsch' },
  { id: 'ja-JP', label: 'Japanese', nativeLabel: '日本語' },
  { id: 'ko-KR', label: 'Korean', nativeLabel: '한국어' },
  { id: 'es-ES', label: 'Spanish', nativeLabel: 'Español' }
];

const EN_MESSAGES = {
  'app.title': 'Legendary: Marvel Randomizer',
  'app.subtitle': 'Browse sets, manage your collection, generate legal setups, and track history with browser-based persistence.',
  'app.documentTitle': 'Legendary: Marvel Randomizer',
  'header.primaryNav': 'Primary',
  'header.primaryNavMobile': 'Primary mobile',
  'header.locale.label': 'Language',
  'header.locale.caption': 'Saved in browser preferences',
  'header.locale.groupLabel': 'Choose language',
  'header.locale.fallbackNotice': 'Some text is using English fallback while this locale pack is still incomplete.',
  'header.theme.label': 'Theme',
  'header.theme.caption': 'Saved in browser preferences',
  'header.theme.groupLabel': 'Choose theme',
  'tabs.browse.label': 'Browse',
  'tabs.collection.label': 'Collection',
  'tabs.new-game.label': 'New Game',
  'tabs.history.label': 'History',
  'tabs.backup.label': 'Backup',
  'tabs.browse.shortLabel': 'Browse',
  'tabs.collection.shortLabel': 'Collection',
  'tabs.new-game.shortLabel': 'New Game',
  'tabs.history.shortLabel': 'History',
  'tabs.backup.shortLabel': 'Backup',
  'tabs.browse.description': 'Explore included sets and collection coverage.',
  'tabs.collection.description': 'Review owned sets, persistence, and usage totals.',
  'tabs.new-game.description': 'Generate, regenerate, and accept setups.',
  'tabs.history.description': 'Inspect accepted setups and reset actions.',
  'tabs.backup.description': 'Export and restore portable app backups.',
  'theme.dark.label': 'Dark',
  'theme.dark.description': 'High-contrast dark command deck styling.',
  'theme.light.label': 'Light',
  'theme.light.description': 'Warm light briefing paper styling.',
  'browse.hero.eyebrow': 'Welcome',
  'browse.hero.title': 'Plan the next Legendary session without the clutter',
  'browse.hero.description': 'Browse every set, mark the collection you own, generate a legal setup, and review play history from one static browser app.',
  'browse.hero.manageCollection': 'Manage Collection',
  'browse.hero.generateGame': 'Generate a Game',
  'browse.hero.replayWalkthrough': 'Replay Walkthrough',
  'browse.hero.aboutProject': 'About this project',
  'browse.metrics.includedSets': 'Included Sets',
  'browse.metrics.ownedSets': 'Owned Sets',
  'browse.metrics.historyRecords': 'History Records',
  'browse.metrics.readyTabs': 'Ready Tabs',
  'browse.startHere.title': 'Start here',
  'browse.startHere.description': 'Use this page as the landing zone: check what the app contains, jump into the workflow, and only open project details when you want them.',
  'browse.startHere.step1Title': '1. Confirm your collection',
  'browse.startHere.step1Body': 'Use Browse or Collection to add owned sets before generating games.',
  'browse.startHere.step2Title': '2. Generate a legal setup',
  'browse.startHere.step2Body': 'New Game respects player mode, collection size, mandatory leads, and freshness history.',
  'browse.startHere.step3Title': '3. Track what you played',
  'browse.startHere.step3Body': 'History and usage reset tools stay available without getting in the way of first-time users.',
  'browse.panel.title': 'Browse sets',
  'browse.panel.description': 'Search by set name or alias, filter by product type, expand a card for contents, and toggle ownership directly from the Browse tab.',
  'browse.visibleSets': 'Visible sets',
  'browse.searchLabel': 'Search sets',
  'browse.searchPlaceholder': 'Search by set name or alias',
  'browse.typeFilter': 'Type filter',
  'browse.emptyFiltered': 'No sets match the current search and filter combination.',
  'browse.set.showDetails': 'Show details',
  'browse.set.hideDetails': 'Hide details',
  'browse.set.inCollection': 'In Collection',
  'browse.set.addToCollection': 'Add to Collection',
  'browse.set.ownedAvailable': 'Owned and available for setup generation.',
  'browse.set.notOwned': 'Not currently owned.',
  'browse.set.aliases': 'Also listed as:',
  'browse.noHeroes': 'No heroes in this set.',
  'browse.noMasterminds': 'No masterminds in this set.',
  'browse.noVillainGroups': 'No villain groups in this set.',
  'browse.noHenchmanGroups': 'No henchman groups in this set.',
  'browse.noSchemes': 'No schemes in this set.',
  'browse.type.all': 'All',
  'browse.type.base': 'Base Game',
  'browse.type.large-expansion': 'Large',
  'browse.type.small-expansion': 'Small',
  'browse.type.standalone': 'Standalone',
  'browse.typeLabel.base': 'Base Game',
  'browse.typeLabel.large-expansion': 'Large Expansion',
  'browse.typeLabel.small-expansion': 'Small Expansion',
  'browse.typeLabel.standalone': 'Standalone',
  'collection.title': 'My Collection',
  'collection.description': 'Manage owned sets here with the same persisted ownership state used by Browse and setup generation.',
  'collection.resetSelections': 'Reset All Selections',
  'collection.ownedSets': 'Owned sets',
  'collection.storage': 'Storage',
  'collection.storage.available': 'Available',
  'collection.storage.unavailable': 'Unavailable',
  'collection.storage.hydrated': 'Hydrated from storage',
  'collection.storage.defaults': 'Using defaults',
  'collection.storage.recovered': 'Recovered on load',
  'collection.storage.clean': 'No recovery needed',
  'collection.latestAction': 'Latest action:',
  'collection.noRecoveryIssues': 'No storage recovery issues are currently active.',
  'collection.totals.title': 'Total available from selected collection',
  'collection.totals.description': 'These totals update immediately as ownership changes from either the Browse tab or this Collection tab.',
  'collection.capacity.title': 'Capacity',
  'collection.capacity.description': 'Warnings use the same legality checks as the setup generator, so thin or uneven collections surface immediately here.',
  'collection.feasibility.legal': 'Legal',
  'collection.feasibility.warning': 'Warning',
  'collection.feasibility.okCopy': 'Collection currently supports this setup mode.',
  'collection.feasibility.badCopy': 'Collection cannot currently support this setup mode.',
  'newGame.playerCount': 'Player count',
  'newGame.playMode': 'Play mode',
  'newGame.resetControls': 'Reset controls',
  'newGame.selectedMode': 'Selected mode',
  'newGame.ownedSets': 'Owned sets',
  'newGame.lastPersistedMode': 'Last persisted mode',
  'newGame.setupRequirements': 'Setup requirements',
  'newGame.twoHandedHelp': 'Two-Handed Solo uses the standard 2-player setup counts while keeping history labeled as a solo game.',
  'newGame.generate': 'Generate Setup',
  'newGame.regenerate': 'Regenerate',
  'newGame.reroll': 'New Setup',
  'newGame.acceptLog': 'Accept & Log',
  'newGame.ephemeralNotice': 'Generate and Regenerate keep the current setup ephemeral. Only Accept & Log updates usage stats and history.',
  'newGame.generator.previewNotice': 'Generate a setup to preview the Epic 3 engine. Regenerate stays ephemeral until you accept.',
  'newGame.generator.freshNotice': 'This setup used fully fresh items in every category.',
  'newGame.result.mastermind': 'Mastermind',
  'newGame.result.scheme': 'Scheme',
  'newGame.result.heroes': 'Heroes',
  'newGame.result.villainGroups': 'Villain Groups',
  'newGame.result.henchmanGroups': 'Henchman Groups',
  'newGame.result.modeBystanders': 'Mode: {mode} · Bystanders: {count}',
  'newGame.result.special': 'Special: {notes}',
  'newGame.forcedPicks.title': 'Forced picks',
  'newGame.forcedPicks.description': 'Force owned Schemes, Masterminds, Heroes, Villain Groups, or Henchman Groups into the next generated setup when legal. These one-shot constraints stay active for Generate and Regenerate, then clear after a successful Accept & Log or a reload.',
  'newGame.forcedPicks.activeConstraints': 'Active constraints',
  'newGame.forcedPicks.clearAll': 'Clear all',
  'newGame.forcedPicks.none': 'No forced picks are active.',
  'newGame.forcedPicks.choose': 'Choose {label}',
  'newGame.forcedPicks.add': 'Add {label}',
  'newGame.forcedPicks.set': 'Set {label}',
  'newGame.forcedPicks.remove': 'Remove',
  'newGame.forcedPicks.forcedBy': 'Forced by {value}',
  'newGame.forcedPicks.field.schemeId': 'Scheme',
  'newGame.forcedPicks.field.mastermindId': 'Mastermind',
  'newGame.forcedPicks.field.heroIds': 'Hero',
  'newGame.forcedPicks.field.villainGroupIds': 'Villain Group',
  'newGame.forcedPicks.field.henchmanGroupIds': 'Henchman Group',
  'newGame.forcedPicks.reason.mastermind': 'Mastermind lead',
  'newGame.forcedPicks.reason.scheme': 'Scheme',
  'newGame.forcedPicks.reason.default': 'Forced pick',
  'history.title': 'Game history',
  'history.description': 'Accepted setups are stored immediately. Each record can stay pending until you log a win/loss and score, then be corrected later if needed.',
  'history.empty': 'No accepted games have been logged yet.',
  'history.groupBy': 'Group by',
  'history.group.mastermind': 'Mastermind',
  'history.group.player-count': 'Players',
  'history.group.play-mode': 'Play Mode',
  'history.group.none': 'Ungrouped',
  'history.group.allGames': 'All games',
  'history.acceptedAt': 'Accepted {date} · {mode}',
  'history.result': 'Result:',
  'history.notes': 'Notes:',
  'history.lastUpdated': 'Last updated {date}',
  'history.scheme': 'Scheme:',
  'history.heroes': 'Heroes:',
  'history.villainGroups': 'Villain Groups:',
  'history.henchmanGroups': 'Henchman Groups:',
  'history.addResult': 'Add result',
  'history.editResult': 'Edit result',
  'history.resultEditor.addTitle': 'Add game result',
  'history.resultEditor.editTitle': 'Edit game result',
  'history.resultEditor.pendingDescription': 'The setup is already logged. Save the outcome now or skip it and come back later from History.',
  'history.resultEditor.editDescription': 'Correct the stored result without duplicating the accepted setup record.',
  'history.resultEditor.outcome': 'Outcome',
  'history.resultEditor.chooseOutcome': 'Choose outcome',
  'history.resultEditor.score': 'Score',
  'history.resultEditor.scoreHint': '(required for wins, optional for losses)',
  'history.resultEditor.notes': 'Notes',
  'history.resultEditor.optional': '(optional)',
  'history.resultEditor.notesPlaceholder': 'Optional notes about the game result',
  'history.resultEditor.save': 'Save result',
  'history.resultEditor.skip': 'Skip for now',
  'history.resultEditor.cancel': 'Cancel',
  'history.insights.title': 'Insights dashboard',
  'history.insights.description': 'Track outcomes, score coverage, and the most- and least-played entities across your owned collection.',
  'history.insights.summary': 'Wins {wins} · Losses {losses} · Pending {pending} · Scored {scored}',
  'history.insights.gamesLogged': 'Games Logged',
  'history.insights.winRate': 'Win Rate',
  'history.insights.pendingResults': 'Pending Results',
  'history.insights.averageScore': 'Average Score',
  'history.insights.bestScore': 'Best Score',
  'history.insights.freshPool': 'Fresh Pool Remaining',
  'history.insights.userCollectionPlayed': 'Your Collection Played',
  'history.insights.overallCollectionPlayed': 'Overall Legendary Played',
  'history.insights.missingExtensions': 'Missing Extensions',
  'history.insights.notOwned': 'not owned',
  'history.insights.helper.unlockTrends': 'Accept and complete a few games to unlock richer trends.',
  'history.insights.helper.noGames': 'No games have been logged yet. Once you accept setups, this section will start showing result and freshness insights.',
  'history.insights.helper.pendingOnly': 'Results are still pending. Save wins or losses in History to unlock outcome and score insights.',
  'history.insights.helper.noScores': 'Completed losses can stay scoreless. Average and best score appear once at least one scored win is logged.',
  'history.insights.helper.oneScore': 'Only one scored game is logged so far, so the recent trend matches that single score.',
  'history.insights.helper.recentAverage': 'Recent average across the last {count} scored {gameWord}: {score}.',
  'history.insights.userCoverage': 'Your collection coverage',
  'history.insights.userCoverageDescription': 'Percentage of the currently owned collection that has been played at least once.',
  'history.insights.overallCoverage': 'Overall Legendary coverage',
  'history.insights.overallCoverageDescription': 'Percentage of the full supported Legendary: Marvel catalog that has been played at least once.',
  'history.insights.mostPlayed': 'Most played',
  'history.insights.leastPlayed': 'Least played used',
  'history.insights.lastUsed': 'Last used {date}',
  'history.insights.noPlayDate': 'No play date recorded',
  'history.insights.playCount': '{count} {playWord}',
  'history.insights.playedSummary': 'Used {used}/{total} · Never played {neverPlayed}',
  'history.insights.noneMostPlayed': 'No {label} have been used in accepted games yet.',
  'history.insights.noneLeastPlayed': 'No used {label} are available to rank yet.',
  'history.coverage.playedSummary': '{played}/{total} played',
  'backup.title': 'Backup and restore',
  'backup.description': 'Export your collection, usage, history, results, and preferences to a versioned JSON backup. Import a backup later and choose whether to merge it into the current state or replace local data entirely.',
  'backup.export': 'Export Backup',
  'backup.import': 'Import Backup',
  'backup.previewTitle': 'Imported backup preview',
  'backup.exportedAt': 'Exported {date}',
  'backup.summary.ownedSets': 'Owned Sets',
  'backup.summary.historyRecords': 'History Records',
  'backup.summary.theme': 'Theme',
  'backup.summary.lastMode': 'Last Mode',
  'backup.summary.usageEntries': 'Usage entries: {value}',
  'backup.mergeReplaceDescription': 'Merge keeps the current app data and unions collection/history while applying imported preferences. Replace swaps the entire saved state for this backup.',
  'backup.merge': 'Merge Backup',
  'backup.replace': 'Replace with Backup',
  'backup.discardPreview': 'Discard Preview',
  'backup.usedCardTracking': 'Used card tracking',
  'backup.usedCardDescription': 'Manage per-category freshness counters and destructive resets from the same data-management screen as backup and restore.',
  'backup.neverPlayed': 'Never played: {value}',
  'backup.resetCategory': 'Reset {label}',
  'backup.lowestPlayReuse': 'Lowest-play reuse activates automatically when a category runs out of never-played options.',
  'backup.resetPreview': 'Reset preview: {historyCount} history entries, {ownedSetCount} owned sets, and clean usage buckets after a full reset.',
  'backup.fullReset': 'Full Reset - Clear all data',
  'onboarding.titleEyebrow': 'First-run walkthrough',
  'onboarding.title': 'Get comfortable with the app in under a minute',
  'onboarding.description': 'This walkthrough is shown on first launch, can be skipped without trapping navigation, and can be replayed anytime from the Browse tab.',
  'onboarding.progress': 'Walkthrough progress',
  'onboarding.previous': 'Previous',
  'onboarding.next': 'Next step',
  'onboarding.finish': 'Finish walkthrough',
  'onboarding.skip': 'Skip for now',
  'onboarding.stepPrefix': 'Step {current} of {total}',
  'onboarding.step1.eyebrow': 'Step 1',
  'onboarding.step1.title': 'Browse the full catalog first',
  'onboarding.step1.description': 'Search by set name or alias, filter by product type, and expand cards to inspect heroes, masterminds, villain groups, henchmen, and schemes.',
  'onboarding.step1.action': 'Stay in Browse',
  'onboarding.step2.eyebrow': 'Step 2',
  'onboarding.step2.title': 'Mark what you actually own',
  'onboarding.step2.description': 'Use Browse or Collection to toggle owned sets, then confirm the collection totals and player-count feasibility before generating setups.',
  'onboarding.step2.action': 'Open Collection',
  'onboarding.step3.eyebrow': 'Step 3',
  'onboarding.step3.title': 'Generate a legal setup',
  'onboarding.step3.description': 'Choose the player mode, generate a setup, and only use Accept & Log once you want the app to update history and freshness tracking.',
  'onboarding.step3.action': 'Open New Game',
  'onboarding.step4.eyebrow': 'Step 4',
  'onboarding.step4.title': 'Review your play history',
  'onboarding.step4.description': 'History shows accepted games, results, and category freshness so you can see what you played recently before setting up the next session.',
  'onboarding.step4.action': 'Open History',
  'onboarding.step5.eyebrow': 'Step 5',
  'onboarding.step5.title': 'Protect your collection with Backup',
  'onboarding.step5.description': 'Use Backup to export your collection and history before risky changes, import a saved snapshot later, and keep reset tools available when you intentionally want a clean slate.',
  'onboarding.step5.action': 'Open Backup',
  'about.eyebrow': 'About this project',
  'about.title': 'Project details and developer diagnostics',
  'about.description': 'This section keeps implementation-oriented details available without putting them in front of players who only want to use the app.',
  'about.hide': 'Hide About',
  'about.initStatus': 'Initialization status',
  'about.dataSamples': 'Data-quality samples',
  'about.testResults': 'Epic 1 test results',
  'about.runtimeDiagnostics': 'Runtime diagnostics',
  'about.persistedState': 'Persisted state snapshot',
  'about.failedInit': 'Foundation loaded with {count} failing Epic 1 test(s).',
  'about.loadedOk': 'Legendary: Marvel Randomizer is loaded successfully with Epic 1-10 implementation, documentation alignment, and automated release-readiness coverage.',
  'about.entries': 'entries',
  'toast.region': 'Notifications',
  'toast.persistent': 'Persistent alert',
  'toast.dismiss': 'Dismiss',
  'toast.acknowledge': 'Acknowledge',
  'toast.variant.success': 'Success',
  'toast.variant.info': 'Info',
  'toast.variant.warning': 'Warning',
  'toast.variant.error': 'Error',
  'modal.cancel': 'Cancel',
  'modal.reset.title': 'Are you sure?',
  'modal.resetCollection.description': 'This will clear all owned collection selections. Usage statistics, history, and preferences will stay intact.',
  'modal.resetCollection.confirm': 'Yes, Clear Collection',
  'modal.resetAll.description': 'This will delete all game history and reset all card tracking. This cannot be undone.',
  'modal.resetAll.confirm': 'Yes, Reset All',
  'modal.merge.title': 'Merge imported backup?',
  'modal.merge.description': 'This will merge {ownedSetCount} owned sets and {historyCount} history records into the current app data, then apply the imported preferences.',
  'modal.merge.confirm': 'Yes, Merge Backup',
  'modal.replace.title': 'Replace current app data?',
  'modal.replace.description': 'This will replace the current local collection, usage, history, and preferences with the imported backup containing {historyCount} history records. This cannot be undone.',
  'modal.replace.confirm': 'Yes, Replace Data',
  'common.heroes': 'Heroes',
  'common.masterminds': 'Masterminds',
  'common.villainGroups': 'Villain Groups',
  'common.henchmanGroups': 'Henchman Groups',
  'common.schemes': 'Schemes',
  'common.theme': 'Theme',
  'common.mode': 'Mode',
  'common.noTeamListed': 'No team listed',
  'common.noMandatoryLead': 'No mandatory lead',
  'common.mandatoryLead': 'Mandatory lead',
  'common.alwaysLeads': 'Always leads: {name}',
  'common.noHistoryYet': 'No accepted games have been logged yet.',
  'common.player': '{count} Player',
  'common.players': '{count} Players',
  'common.game': 'game',
  'common.games': 'games',
  'common.play': 'play',
  'common.plays': 'plays',
  'common.hero': 'hero',
  'common.heroTitle': 'Hero',
  'common.heroesLower': 'heroes',
  'common.mastermind': 'mastermind',
  'common.mastermindTitle': 'Mastermind',
  'common.mastermindsLower': 'masterminds',
  'common.villainGroup': 'villain group',
  'common.villainGroupTitle': 'Villain Group',
  'common.villainGroupsLower': 'villain groups',
  'common.henchmanGroup': 'henchman group',
  'common.henchmanGroupTitle': 'Henchman Group',
  'common.henchmanGroupsLower': 'henchman groups',
  'common.scheme': 'scheme',
  'common.schemeTitle': 'Scheme',
  'common.schemesLower': 'schemes',
  'common.wound': 'Wound',
  'common.wounds': 'Wounds',
  'collection.group.base': 'Base',
  'collection.group.large-expansion': 'Large Expansions',
  'collection.group.small-expansion': 'Small Expansions',
  'collection.group.standalone': 'Standalone',
  'newGame.panel.setupTitle': 'Setup engine preview',
  'newGame.panel.resultTitle': 'Generated setup result',
  'common.outcome.win': 'Win',
  'common.outcome.loss': 'Loss',
  'common.pendingResult': 'Pending result',
  'common.score': 'Score {score}',
  'common.unknown': 'Unknown',
  'common.playMode.standard': 'Standard',
  'common.playMode.standardSolo': 'Standard Solo',
  'common.playMode.advanced-solo': 'Advanced Solo',
  'common.playMode.two-handed-solo': 'Two-Handed Solo',
  'common.playMode.standardDescription': 'Use the standard setup counts for the selected player count.',
  'common.playMode.standardSoloDescription': 'Use the standard 1-player setup counts.',
  'common.playMode.advanced-soloDescription': 'Use the Advanced Solo setup counts with 4 Heroes and 2 Villain Groups.',
  'common.playMode.two-handed-soloDescription': 'Track the game as solo, but use the standard 2-player setup counts.',
  'common.playMode.multiplayerDisabled': 'Alternate solo modes are disabled until you switch back to 1 player.',
  'common.playMode.twoHandedHelp': 'Two-Handed Solo keeps the game labeled as solo, but uses the standard 2-player setup counts.',
  'common.playMode.chooseSolo': 'Choose between Standard Solo, Advanced Solo, and Two-Handed Solo while staying in 1-player mode.',
  'common.format.persistedPlayMode': '{players}P · {mode}',
  'actions.switchedTab': 'Switched to the {tab} tab.',
  'actions.keyboardTabs': 'Switched tabs with keyboard navigation.',
  'actions.keyboardFirstTab': 'Jumped to the first tab with keyboard navigation.',
  'actions.keyboardLastTab': 'Jumped to the last tab with keyboard navigation.',
  'actions.updatedHistoryGrouping': 'Updated History grouping to {mode}.',
  'actions.updatedOwnedCollection': 'Updated owned collection state. Generate a new setup to use the current collection.',
  'actions.openedAbout': 'Opened the About this project panel.',
  'actions.closedAbout': 'Closed the About this project panel.',
  'actions.openedWalkthrough': 'Opened the introductory walkthrough.',
  'actions.replayWalkthrough': 'Returned to the Browse tab to replay the walkthrough.',
  'actions.previousWalkthrough': 'Moved to the previous walkthrough step.',
  'actions.nextWalkthrough': 'Moved to the next walkthrough step.',
  'actions.openedWalkthroughTab': 'Opened the {tab} tab from the walkthrough.',
  'actions.skippedWalkthrough': 'Skipped the walkthrough. Replay it anytime from Browse.',
  'actions.completedWalkthrough': 'Completed the walkthrough. Replay it anytime from Browse.',
  'actions.confirmResetCollection': 'Confirm clearing the owned collection to remove all current selections.',
  'actions.keptCollection': 'Kept the current owned collection selections.',
  'actions.clearedCollection': 'Cleared all owned collection selections.',
  'actions.confirmResetAll': 'Confirm the full reset to clear collection, usage, history, and preferences.',
  'actions.keptState': 'Kept the current persisted application state.',
  'actions.selectedPlayerMode': 'Selected {count} {playerWord} setup mode.',
  'actions.invalidSoloMode': 'Alternate solo modes are only available for 1 player.',
  'actions.selectedPlayMode': 'Selected {mode} mode.',
  'actions.appliedTheme': 'Applied the {theme} theme.',
  'actions.appliedLocale': 'Applied the {locale} language.',
  'actions.exportedBackup': 'Exported a backup to {fileName}.',
  'actions.exportedBackupToast': 'Exported backup as {fileName}.',
  'actions.backupImportFailed': 'The selected backup file could not be imported.',
  'actions.loadedBackupPreview': 'Loaded a backup preview. Choose Merge or Replace to apply it.',
  'actions.discardedBackupPreview': 'Discarded the staged backup preview.',
  'actions.reviewMerge': 'Review the merge confirmation before applying the imported backup.',
  'actions.reviewReplace': 'Review the replace confirmation before applying the imported backup.',
  'actions.keptBackupPreview': 'Kept the staged backup preview without applying it.',
  'actions.mergedBackup': 'Merged the imported backup with the current app data.',
  'actions.replacedBackup': 'Replaced the current app data with the imported backup.',
  'actions.chooseForcedPick': 'Choose a card or setup entity before adding a forced pick.',
  'actions.updatedForcedPicks': 'Updated the active forced picks for the next generated setup.',
  'actions.duplicateForcedPick': 'That forced pick was already active.',
  'actions.removedForcedPick': 'Removed one forced pick from the next generated setup.',
  'actions.clearedForcedPicks': 'Cleared all forced picks for the next generated setup.',
  'actions.generatedSetup': 'Generated a new setup without mutating persisted usage or history.',
  'actions.failedSetup': 'Could not generate a legal setup for the current collection.',
  'actions.regeneratedSetup': 'Regenerated the current setup without mutating persisted state.',
  'actions.acceptBeforeLog': 'Generate a setup before using Accept & Log.',
  'actions.acceptedLoggedForced': 'Accepted and logged the current generated setup, opened score entry, and cleared the one-shot forced picks.',
  'actions.acceptedLogged': 'Accepted and logged the current generated setup and opened score entry in History.',
  'actions.acceptedToast': 'Accepted and logged the current generated setup. Add the result now or skip it for later.',
  'actions.openedResultEditor': 'Opened result editing for the selected history record.',
  'actions.pendingResult': 'Left the selected game result pending. You can add it later from History.',
  'actions.pendingResultToast': 'Kept the selected game result pending.',
  'actions.closedResultEditor': 'Closed result editing without changing the stored history record.',
  'actions.finishResultFields': 'Finish the required result fields before saving.',
  'actions.savedResult': 'Saved the game result for the selected history record.',
  'actions.savedCorrectedResult': 'Saved the corrected game result for the selected history record.',
  'actions.savedResultToast': 'Saved the game result.',
  'actions.savedCorrectedResultToast': 'Saved the corrected game result.',
  'actions.resetUsageStats': 'Reset {label} usage stats.',
  'actions.resetAllDefaults': 'Reset the entire application state to defaults.',
  'actions.clearDefaults': 'Reset the current setup controls to their default values.',
  'persistence.invalidPrefs': 'Recovered invalid preference values during state hydration.',
  'validation.chooseOutcome': 'Choose Win or Loss before saving the result.',
  'validation.enterWinScore': 'Enter a score before saving the result.',
  'validation.scoreWholeNumber': 'Score must be a whole number that is 0 or greater.'
};

const FR_MESSAGES = {
  'app.title': 'Randomiseur Legendary: Marvel',
  'app.subtitle': 'Parcourez les extensions, gerez votre collection, generez des mises en place valides et suivez votre historique avec une sauvegarde dans le navigateur.',
  'app.documentTitle': 'Randomiseur Legendary: Marvel',
  'header.primaryNav': 'Navigation principale',
  'header.primaryNavMobile': 'Navigation mobile principale',
  'header.locale.label': 'Langue',
  'header.locale.caption': 'Enregistree dans les preferences du navigateur',
  'header.locale.groupLabel': 'Choisir la langue',
  'header.locale.fallbackNotice': 'Certains textes utilisent encore le repli en anglais pendant que ce pack de langue reste incomplet.',
  'header.theme.label': 'Theme',
  'header.theme.caption': 'Enregistre dans les preferences du navigateur',
  'header.theme.groupLabel': 'Choisir le theme',
  'tabs.browse.label': 'Parcourir',
  'tabs.collection.label': 'Collection',
  'tabs.new-game.label': 'Nouvelle partie',
  'tabs.history.label': 'Historique',
  'tabs.backup.label': 'Sauvegarde',
  'tabs.browse.shortLabel': 'Parcourir',
  'tabs.collection.shortLabel': 'Collection',
  'tabs.new-game.shortLabel': 'Partie',
  'tabs.history.shortLabel': 'Historique',
  'tabs.backup.shortLabel': 'Sauvegarde',
  'tabs.browse.description': 'Explorer les extensions incluses et la couverture de collection.',
  'tabs.collection.description': 'Verifier les extensions possedees, la persistance et les totaux d utilisation.',
  'tabs.new-game.description': 'Generer, regenerer et accepter des mises en place.',
  'tabs.history.description': 'Examiner les parties acceptees et les actions de reinitialisation.',
  'tabs.backup.description': 'Exporter et restaurer des sauvegardes portables de l application.',
  'theme.dark.label': 'Sombre',
  'theme.dark.description': 'Style sombre a contraste eleve inspire d un poste de commandement.',
  'theme.light.label': 'Clair',
  'theme.light.description': 'Style clair et chaud de briefing imprime.',
  'browse.hero.eyebrow': 'Bienvenue',
  'browse.hero.title': 'Preparez la prochaine session Legendary sans surcharge',
  'browse.hero.description': 'Parcourez toutes les extensions, marquez votre collection, generez une mise en place valide et relisez votre historique depuis une application statique.',
  'browse.hero.manageCollection': 'Gerer la collection',
  'browse.hero.generateGame': 'Generer une partie',
  'browse.hero.replayWalkthrough': 'Rejouer la visite',
  'browse.hero.aboutProject': 'A propos du projet',
  'browse.metrics.includedSets': 'Extensions incluses',
  'browse.metrics.ownedSets': 'Extensions possedees',
  'browse.metrics.historyRecords': 'Parties enregistrees',
  'browse.metrics.readyTabs': 'Onglets prets',
  'browse.startHere.title': 'Commencez ici',
  'browse.startHere.description': 'Utilisez cette page comme point d entree: verifiez ce que contient l application, sautez vers le flux principal, puis ouvrez les details du projet seulement si vous en avez besoin.',
  'browse.startHere.step1Title': '1. Confirmez votre collection',
  'browse.startHere.step1Body': 'Utilisez Parcourir ou Collection pour ajouter vos extensions avant de generer des parties.',
  'browse.startHere.step2Title': '2. Generez une mise en place valide',
  'browse.startHere.step2Body': 'Nouvelle partie respecte le mode de jeu, la taille de collection, les meneurs obligatoires et l historique de fraicheur.',
  'browse.startHere.step3Title': '3. Suivez vos parties',
  'browse.startHere.step3Body': 'Historique et les outils de reinitialisation restent disponibles sans gener les nouveaux utilisateurs.',
  'browse.panel.title': 'Parcourir les extensions',
  'browse.panel.description': 'Recherchez par nom ou alias, filtrez par type de produit, ouvrez une carte pour son contenu et gerez la possession directement depuis l onglet Parcourir.',
  'browse.visibleSets': 'Extensions visibles',
  'browse.searchLabel': 'Rechercher des extensions',
  'browse.searchPlaceholder': 'Rechercher par nom ou alias',
  'browse.typeFilter': 'Filtre par type',
  'browse.emptyFiltered': 'Aucune extension ne correspond a la recherche et au filtre actuels.',
  'browse.set.showDetails': 'Afficher les details',
  'browse.set.hideDetails': 'Masquer les details',
  'browse.set.inCollection': 'Dans la collection',
  'browse.set.addToCollection': 'Ajouter a la collection',
  'browse.set.ownedAvailable': 'Possedee et disponible pour la generation.',
  'browse.set.notOwned': 'Non posee actuellement.',
  'browse.set.aliases': 'Egalement liste sous :',
  'browse.noHeroes': 'Aucun heros dans cette extension.',
  'browse.noMasterminds': 'Aucun mastermind dans cette extension.',
  'browse.noVillainGroups': 'Aucun groupe de vilains dans cette extension.',
  'browse.noHenchmanGroups': 'Aucun groupe de sbires dans cette extension.',
  'browse.noSchemes': 'Aucun plan dans cette extension.',
  'browse.type.all': 'Tous',
  'browse.type.base': 'Base',
  'browse.type.large-expansion': 'Grande',
  'browse.type.small-expansion': 'Petite',
  'browse.type.standalone': 'Autonome',
  'browse.typeLabel.base': 'Base',
  'browse.typeLabel.large-expansion': 'Grande extension',
  'browse.typeLabel.small-expansion': 'Petite extension',
  'browse.typeLabel.standalone': 'Autonome',
  'collection.title': 'Ma collection',
  'collection.description': 'Gerez ici les extensions possedees avec le meme etat persistant utilise par Parcourir et la generation.',
  'collection.resetSelections': 'Reinitialiser toutes les selections',
  'collection.ownedSets': 'Extensions possedees',
  'collection.storage': 'Stockage',
  'collection.storage.available': 'Disponible',
  'collection.storage.unavailable': 'Indisponible',
  'collection.storage.hydrated': 'Charge depuis le stockage',
  'collection.storage.defaults': 'Valeurs par defaut',
  'collection.storage.recovered': 'Recupere au chargement',
  'collection.storage.clean': 'Aucune recuperation necessaire',
  'collection.latestAction': 'Derniere action :',
  'collection.noRecoveryIssues': 'Aucun probleme de recuperation du stockage n est actuellement actif.',
  'collection.totals.title': 'Total disponible dans la collection selectionnee',
  'collection.totals.description': 'Ces totaux se mettent a jour immediatement quand la possession change depuis Parcourir ou Collection.',
  'collection.capacity.title': 'Capacite',
  'collection.capacity.description': 'Les alertes utilisent les memes controles de legalite que le generateur, donc les collections trop fines apparaissent ici tout de suite.',
  'collection.feasibility.legal': 'Valide',
  'collection.feasibility.warning': 'Alerte',
  'collection.feasibility.okCopy': 'La collection prend actuellement en charge ce mode.',
  'collection.feasibility.badCopy': 'La collection ne prend pas encore en charge ce mode.',
  'newGame.playerCount': 'Nombre de joueurs',
  'newGame.playMode': 'Mode de jeu',
  'newGame.resetControls': 'Reinitialiser les controles',
  'newGame.selectedMode': 'Mode selectionne',
  'newGame.ownedSets': 'Extensions possedees',
  'newGame.lastPersistedMode': 'Dernier mode persiste',
  'newGame.setupRequirements': 'Exigences de mise en place',
  'newGame.twoHandedHelp': 'Solo a deux mains utilise les quantites du mode 2 joueurs tout en gardant un historique marque solo.',
  'newGame.generate': 'Generer la mise en place',
  'newGame.regenerate': 'Regenerer',
  'newGame.reroll': 'Nouvelle mise en place',
  'newGame.acceptLog': 'Accepter et enregistrer',
  'newGame.ephemeralNotice': 'Generer et Regenerer gardent la mise en place ephemere. Seul Accepter et enregistrer met a jour l historique et l usage.',
  'newGame.generator.previewNotice': 'Generez une mise en place pour previsualiser le moteur Epic 3. Regenerer reste ephemere tant que vous n acceptez pas.',
  'newGame.generator.freshNotice': 'Cette mise en place a utilise des elements totalement frais dans chaque categorie.',
  'newGame.result.mastermind': 'Mastermind',
  'newGame.result.scheme': 'Plan',
  'newGame.result.heroes': 'Heros',
  'newGame.result.villainGroups': 'Groupes de vilains',
  'newGame.result.henchmanGroups': 'Groupes de sbires',
  'newGame.result.modeBystanders': 'Mode : {mode} · Passants : {count}',
  'newGame.result.special': 'Special : {notes}',
  'newGame.forcedPicks.title': 'Selections forcees',
  'newGame.forcedPicks.description': 'Forcez des Plans, Masterminds, Heros, Groupes de vilains ou Groupes de sbires possedes dans la prochaine mise en place lorsque c est legal. Ces contraintes a usage unique restent actives pour Generer et Regenerer, puis disparaissent apres un Accepter et enregistrer reussi ou un rechargement.',
  'newGame.forcedPicks.activeConstraints': 'Contraintes actives',
  'newGame.forcedPicks.clearAll': 'Tout effacer',
  'newGame.forcedPicks.none': 'Aucune selection forcee active.',
  'history.title': 'Historique des parties',
  'history.description': 'Les mises en place acceptees sont enregistrees immediatement. Chaque entree peut rester en attente jusqu a l enregistrement d une victoire ou d une defaite et d un score, puis etre corrigee plus tard si necessaire.',
  'history.empty': 'Aucune partie acceptee n a encore ete enregistree.',
  'history.groupBy': 'Regrouper par',
  'history.group.mastermind': 'Mastermind',
  'history.group.player-count': 'Joueurs',
  'history.group.play-mode': 'Mode de jeu',
  'history.group.none': 'Sans regroupement',
  'history.group.allGames': 'Toutes les parties',
  'history.acceptedAt': 'Acceptee {date} · {mode}',
  'history.result': 'Resultat :',
  'history.notes': 'Notes :',
  'history.lastUpdated': 'Derniere mise a jour {date}',
  'history.scheme': 'Plan :',
  'history.heroes': 'Heros :',
  'history.villainGroups': 'Groupes de vilains :',
  'history.henchmanGroups': 'Groupes de sbires :',
  'history.addResult': 'Ajouter le resultat',
  'history.editResult': 'Modifier le resultat',
  'history.resultEditor.addTitle': 'Ajouter le resultat de partie',
  'history.resultEditor.editTitle': 'Modifier le resultat de partie',
  'history.resultEditor.pendingDescription': 'La mise en place est deja enregistree. Sauvegardez le resultat maintenant ou revenez plus tard depuis Historique.',
  'history.resultEditor.editDescription': 'Corrigez le resultat stocke sans dupliquer l entree acceptee.',
  'history.resultEditor.outcome': 'Issue',
  'history.resultEditor.chooseOutcome': 'Choisir une issue',
  'history.resultEditor.score': 'Score',
  'history.resultEditor.scoreHint': '(obligatoire pour une victoire, facultatif pour une defaite)',
  'history.resultEditor.notes': 'Notes',
  'history.resultEditor.optional': '(facultatif)',
  'history.resultEditor.notesPlaceholder': 'Notes facultatives sur le resultat de partie',
  'history.resultEditor.save': 'Enregistrer le resultat',
  'history.resultEditor.skip': 'Ignorer pour le moment',
  'history.resultEditor.cancel': 'Annuler',
  'history.insights.title': 'Tableau de bord',
  'history.insights.description': 'Suivez les resultats, la couverture des scores et les elements les plus et les moins joues dans votre collection.',
  'history.insights.summary': 'Victoires {wins} · Defaites {losses} · En attente {pending} · Scores {scored}',
  'history.insights.gamesLogged': 'Parties enregistrees',
  'history.insights.winRate': 'Taux de victoire',
  'history.insights.pendingResults': 'Resultats en attente',
  'history.insights.averageScore': 'Score moyen',
  'history.insights.bestScore': 'Meilleur score',
  'history.insights.freshPool': 'Reserve fraiche restante',
  'history.insights.userCollectionPlayed': 'Votre collection jouee',
  'history.insights.overallCollectionPlayed': 'Legendary global joue',
  'history.insights.missingExtensions': 'Extensions manquantes',
  'history.insights.notOwned': 'non possede',
  'backup.title': 'Sauvegarde et restauration',
  'backup.description': 'Exportez votre collection, usage, historique, resultats et preferences dans une sauvegarde JSON versionnee. Importez ensuite une sauvegarde et choisissez de la fusionner avec l etat courant ou de remplacer entierement les donnees locales.',
  'backup.export': 'Exporter la sauvegarde',
  'backup.import': 'Importer une sauvegarde',
  'backup.previewTitle': 'Apercu de la sauvegarde importee',
  'backup.exportedAt': 'Exportee {date}',
  'backup.summary.ownedSets': 'Extensions possedees',
  'backup.summary.historyRecords': 'Entrees d historique',
  'backup.summary.theme': 'Theme',
  'backup.summary.lastMode': 'Dernier mode',
  'backup.summary.usageEntries': 'Entrees d usage : {value}',
  'backup.mergeReplaceDescription': 'Fusionner conserve les donnees actuelles et unite collection et historique tout en appliquant les preferences importees. Remplacer substitue completement l etat sauvegarde par cette sauvegarde.',
  'backup.merge': 'Fusionner la sauvegarde',
  'backup.replace': 'Remplacer par la sauvegarde',
  'backup.discardPreview': 'Ignorer l apercu',
  'backup.usedCardTracking': 'Suivi des cartes utilisees',
  'backup.usedCardDescription': 'Gerez les compteurs de fraicheur par categorie et les reinitialisations destructrices depuis le meme ecran de gestion des donnees.',
  'backup.neverPlayed': 'Jamais joue : {value}',
  'backup.resetCategory': 'Reinitialiser {label}',
  'backup.lowestPlayReuse': 'La reutilisation des elements les moins joues s active automatiquement quand une categorie n a plus d options jamais jouees.',
  'backup.resetPreview': 'Apercu de reinitialisation : {historyCount} entrees d historique, {ownedSetCount} extensions possedees et des compartiments d usage vierges apres une reinitialisation complete.',
  'backup.fullReset': 'Reinitialisation complete - Effacer toutes les donnees',
  'onboarding.titleEyebrow': 'Visite de premiere ouverture',
  'onboarding.title': 'Prenez l application en main en moins d une minute',
  'onboarding.description': 'Cette visite apparait au premier lancement, peut etre ignoree sans bloquer la navigation et peut etre relancee a tout moment depuis Parcourir.',
  'onboarding.progress': 'Progression de la visite',
  'onboarding.previous': 'Precedent',
  'onboarding.next': 'Etape suivante',
  'onboarding.finish': 'Terminer la visite',
  'onboarding.skip': 'Ignorer pour le moment',
  'onboarding.stepPrefix': 'Etape {current} sur {total}',
  'onboarding.step1.eyebrow': 'Etape 1',
  'onboarding.step1.title': 'Parcourez d abord tout le catalogue',
  'onboarding.step1.description': 'Recherchez par nom d extension ou alias, filtrez par type de produit et developpez les cartes pour examiner heros, masterminds, groupes de vilains, groupes de sbires et plans.',
  'onboarding.step1.action': 'Rester dans Parcourir',
  'onboarding.step2.eyebrow': 'Etape 2',
  'onboarding.step2.title': 'Indiquez ce que vous possedez vraiment',
  'onboarding.step2.description': 'Utilisez Parcourir ou Collection pour basculer les extensions possedees, puis confirmez les totaux de collection et la faisabilite selon le nombre de joueurs avant de generer une mise en place.',
  'onboarding.step2.action': 'Ouvrir Collection',
  'onboarding.step3.eyebrow': 'Etape 3',
  'onboarding.step3.title': 'Generez une mise en place legale',
  'onboarding.step3.description': 'Choisissez le mode de jeu, generez une mise en place et n utilisez Accepter et enregistrer que lorsque vous voulez mettre a jour l historique et le suivi de fraicheur.',
  'onboarding.step3.action': 'Ouvrir Nouvelle partie',
  'onboarding.step4.eyebrow': 'Etape 4',
  'onboarding.step4.title': 'Consultez votre historique de parties',
  'onboarding.step4.description': 'L historique affiche les parties acceptees, les resultats et la fraicheur par categorie afin de voir ce que vous avez joue recemment avant la prochaine session.',
  'onboarding.step4.action': 'Ouvrir Historique',
  'onboarding.step5.eyebrow': 'Etape 5',
  'onboarding.step5.title': 'Protegez votre collection avec Sauvegarde',
  'onboarding.step5.description': 'Utilisez Sauvegarde pour exporter votre collection et votre historique avant une modification risquee, reimporter un instantane plus tard et garder les reinitialisations pour les cas ou vous voulez vraiment repartir de zero.',
  'onboarding.step5.action': 'Ouvrir Sauvegarde',
  'about.eyebrow': 'A propos du projet',
  'about.title': 'Details du projet et diagnostics de developpement',
  'about.description': 'Cette section garde les details techniques disponibles sans les imposer aux joueurs qui veulent seulement utiliser l application.',
  'about.hide': 'Masquer A propos',
  'about.entries': 'entrees',
  'toast.region': 'Notifications',
  'toast.persistent': 'Alerte persistante',
  'toast.dismiss': 'Fermer',
  'toast.acknowledge': 'Confirmer',
  'toast.variant.success': 'Succes',
  'toast.variant.info': 'Info',
  'toast.variant.warning': 'Alerte',
  'toast.variant.error': 'Erreur',
  'modal.cancel': 'Annuler',
  'modal.reset.title': 'Confirmer ?',
  'modal.resetCollection.description': 'Cela effacera toutes les selections de collection possedee. Les statistiques d usage, l historique et les preferences resteront intacts.',
  'modal.resetCollection.confirm': 'Oui, effacer la collection',
  'modal.resetAll.description': 'Cela supprimera tout l historique et reinitialisera tout le suivi des cartes. Cette action est irreversible.',
  'modal.resetAll.confirm': 'Oui, tout reinitialiser',
  'modal.merge.title': 'Fusionner la sauvegarde importee ?',
  'modal.replace.title': 'Remplacer les donnees actuelles ?',
  'common.heroes': 'Heros',
  'common.masterminds': 'Masterminds',
  'common.villainGroups': 'Groupes de vilains',
  'common.henchmanGroups': 'Groupes de sbires',
  'common.schemes': 'Plans',
  'common.noTeamListed': 'Aucune equipe indiquee',
  'common.noMandatoryLead': 'Aucun meneur obligatoire',
  'common.mandatoryLead': 'Meneur obligatoire',
  'common.alwaysLeads': 'Dirige toujours : {name}',
  'common.player': '{count} joueur',
  'common.players': '{count} joueurs',
  'common.game': 'partie',
  'common.games': 'parties',
  'common.play': 'partie jouee',
  'common.plays': 'parties jouees',
  'common.hero': 'heros',
  'common.heroTitle': 'Heros',
  'common.heroesLower': 'heros',
  'common.mastermind': 'mastermind',
  'common.mastermindTitle': 'Mastermind',
  'common.mastermindsLower': 'masterminds',
  'common.villainGroup': 'groupe de vilains',
  'common.villainGroupTitle': 'Groupe de vilains',
  'common.villainGroupsLower': 'groupes de vilains',
  'common.henchmanGroup': 'groupe de sbires',
  'common.henchmanGroupTitle': 'Groupe de sbires',
  'common.henchmanGroupsLower': 'groupes de sbires',
  'common.scheme': 'plan',
  'common.schemeTitle': 'Plan',
  'common.schemesLower': 'plans',
  'common.wound': 'Blessure',
  'common.wounds': 'Blessures',
  'collection.group.base': 'Base',
  'collection.group.large-expansion': 'Grandes extensions',
  'collection.group.small-expansion': 'Petites extensions',
  'collection.group.standalone': 'Autonome',
  'newGame.panel.setupTitle': 'Apercu du moteur de mise en place',
  'newGame.panel.resultTitle': 'Resultat de la mise en place',
  'common.outcome.win': 'Victoire',
  'common.outcome.loss': 'Defaite',
  'common.pendingResult': 'Resultat en attente',
  'common.score': 'Score {score}',
  'common.playMode.standard': 'Standard',
  'common.playMode.standardSolo': 'Solo standard',
  'common.playMode.advanced-solo': 'Solo avance',
  'common.playMode.two-handed-solo': 'Solo a deux mains',
  'common.playMode.standardDescription': 'Utilise les quantites standard pour le nombre de joueurs selectionne.',
  'common.playMode.standardSoloDescription': 'Utilise les quantites standard a 1 joueur.',
  'common.playMode.advanced-soloDescription': 'Utilise les quantites du mode Solo avance avec 4 Heros et 2 Groupes de vilains.',
  'common.playMode.two-handed-soloDescription': 'Suit la partie comme une partie solo, mais utilise les quantites du mode standard 2 joueurs.',
  'common.playMode.multiplayerDisabled': 'Les autres modes solo sont desactives tant que vous ne revenez pas a 1 joueur.',
  'common.playMode.twoHandedHelp': 'Solo a deux mains garde une etiquette solo, mais utilise les quantites du mode standard 2 joueurs.',
  'common.playMode.chooseSolo': 'Choisissez entre Solo standard, Solo avance et Solo a deux mains en restant a 1 joueur.',
  'common.format.persistedPlayMode': '{players}J · {mode}',
  'actions.appliedLocale': 'Langue appliquee : {locale}.',
  'persistence.invalidPrefs': 'Des valeurs de preference invalides ont ete recuperees pendant l hydratation.',
  'validation.chooseOutcome': 'Choisissez Victoire ou Defaite avant d enregistrer le resultat.',
  'validation.enterWinScore': 'Saisissez un score avant d enregistrer le resultat.',
  'validation.scoreWholeNumber': 'Le score doit etre un entier superieur ou egal a 0.'
};

const DE_MESSAGES = {
  'app.title': 'Legendary: Marvel Zufallsgenerator',
  'app.subtitle': 'Durchsuche Sets, verwalte deine Sammlung, generiere legale Aufstellungen und verfolge den Verlauf mit Speicherung im Browser.',
  'header.locale.label': 'Sprache',
  'header.locale.caption': 'In den Browser-Einstellungen gespeichert',
  'header.locale.groupLabel': 'Sprache auswählen',
  'header.theme.label': 'Thema',
  'header.theme.caption': 'In den Browser-Einstellungen gespeichert',
  'header.theme.groupLabel': 'Thema auswählen',
  'tabs.browse.label': 'Stöbern',
  'tabs.collection.label': 'Sammlung',
  'tabs.new-game.label': 'Neues Spiel',
  'tabs.history.label': 'Verlauf',
  'tabs.backup.label': 'Backup',
  'tabs.browse.shortLabel': 'Stöbern',
  'tabs.collection.shortLabel': 'Sammlung',
  'tabs.new-game.shortLabel': 'Spiel',
  'tabs.history.shortLabel': 'Verlauf',
  'tabs.backup.shortLabel': 'Backup',
  'browse.hero.eyebrow': 'Willkommen',
  'browse.hero.title': 'Plane die nächste Legendary-Session ohne Ballast',
  'browse.hero.description': 'Durchsuche alle Sets, markiere deine Sammlung, generiere eine legale Aufstellung und prüfe den Spielverlauf in einer statischen Browser-App.',
  'browse.hero.manageCollection': 'Sammlung verwalten',
  'browse.hero.generateGame': 'Spiel generieren',
  'browse.hero.replayWalkthrough': 'Einführung wiederholen',
  'browse.hero.aboutProject': 'Über dieses Projekt',
  'browse.metrics.includedSets': 'Enthaltene Sets',
  'browse.metrics.ownedSets': 'Besessene Sets',
  'browse.metrics.historyRecords': 'Verlaufseinträge',
  'browse.metrics.readyTabs': 'Bereite Tabs',
  'browse.startHere.title': 'Hier starten',
  'browse.startHere.description': 'Nutze diese Seite als Einstieg: prüfe den Inhalt der App, springe in den Ablauf und öffne Projektdetails nur bei Bedarf.',
  'browse.startHere.step1Title': '1. Bestätige deine Sammlung',
  'browse.startHere.step1Body': 'Nutze Stöbern oder Sammlung, um besessene Sets vor der Spielgenerierung hinzuzufügen.',
  'browse.startHere.step2Title': '2. Generiere eine legale Aufstellung',
  'browse.startHere.step2Body': 'Neues Spiel berücksichtigt Modus, Sammlungsgröße, Pflichtleads und Frischeverlauf.',
  'browse.startHere.step3Title': '3. Verfolge, was du gespielt hast',
  'browse.startHere.step3Body': 'Verlauf und Reset-Werkzeuge bleiben verfügbar, ohne neue Nutzer auszubremsen.',
  'browse.panel.title': 'Sets durchsuchen',
  'browse.panel.description': 'Suche nach Setnamen oder Alias, filtere nach Produkttyp, öffne Karteninhalte und ändere Besitz direkt im Stöbern-Tab.',
  'browse.visibleSets': 'Sichtbare Sets',
  'browse.searchLabel': 'Sets suchen',
  'browse.searchPlaceholder': 'Nach Setname oder Alias suchen',
  'browse.typeFilter': 'Typfilter',
  'browse.emptyFiltered': 'Keine Sets entsprechen der aktuellen Suche und dem Filter.',
  'browse.set.showDetails': 'Details anzeigen',
  'browse.set.hideDetails': 'Details ausblenden',
  'browse.set.inCollection': 'In Sammlung',
  'browse.set.addToCollection': 'Zur Sammlung hinzufügen',
  'browse.set.ownedAvailable': 'Besessen und für die Generierung verfügbar.',
  'browse.set.notOwned': 'Derzeit nicht besessen.',
  'browse.set.aliases': 'Auch gelistet als:',
  'browse.noHeroes': 'Keine Helden in diesem Set.',
  'browse.noMasterminds': 'Keine Masterminds in diesem Set.',
  'browse.noVillainGroups': 'Keine Schurkengruppen in diesem Set.',
  'browse.noHenchmanGroups': 'Keine Handlangergruppen in diesem Set.',
  'browse.noSchemes': 'Keine Pläne in diesem Set.',
  'collection.title': 'Meine Sammlung',
  'collection.description': 'Verwalte hier besessene Sets mit demselben gespeicherten Besitzstatus, den Stöbern und Generierung verwenden.',
  'collection.resetSelections': 'Alle Auswahlen zurücksetzen',
  'newGame.playerCount': 'Spieleranzahl',
  'newGame.playMode': 'Spielmodus',
  'newGame.generate': 'Aufstellung generieren',
  'newGame.regenerate': 'Neu generieren',
  'newGame.reroll': 'Neue Aufstellung',
  'newGame.acceptLog': 'Übernehmen und protokollieren',
  'history.title': 'Spielverlauf',
  'history.description': 'Übernommene Aufstellungen werden sofort gespeichert. Jeder Eintrag kann offen bleiben, bis du Sieg/Niederlage und Punktzahl speicherst.',
  'history.insights.title': 'Erkenntnisse',
  'backup.title': 'Backup und Wiederherstellung',
  'backup.description': 'Exportiere Sammlung, Nutzung, Verlauf, Ergebnisse und Einstellungen in ein versioniertes JSON-Backup. Importiere es später und führe es zusammen oder ersetze lokale Daten vollständig.',
  'backup.export': 'Backup exportieren',
  'backup.import': 'Backup importieren',
  'onboarding.titleEyebrow': 'Erststart-Einfuhrung',
  'onboarding.title': 'Lerne die App in unter einer Minute kennen',
  'onboarding.previous': 'Zurück',
  'onboarding.next': 'Nächster Schritt',
  'onboarding.finish': 'Einführung beenden',
  'onboarding.skip': 'Vorerst überspringen',
  'onboarding.stepPrefix': 'Schritt {current} von {total}',
  'onboarding.step1.eyebrow': 'Schritt 1',
  'onboarding.step1.title': 'Durchsuche zuerst den gesamten Katalog',
  'onboarding.step1.description': 'Suche nach Setnamen oder Aliasen, filtere nach Produkttyp und erweitere Karten, um Helden, Masterminds, Schurkengruppen, Handlangergruppen und Plaene zu pruifen.',
  'onboarding.step1.action': 'Im Stoebern bleiben',
  'onboarding.step2.eyebrow': 'Schritt 2',
  'onboarding.step2.title': 'Markiere, was du wirklich besitzt',
  'onboarding.step2.description': 'Nutze Stoebern oder Sammlung, um besessene Sets umzuschalten, und bestaetige dann Sammlungssummen und Machbarkeit fuer die Spieleranzahl, bevor du Aufstellungen erzeugst.',
  'onboarding.step2.action': 'Sammlung oeffnen',
  'onboarding.step3.eyebrow': 'Schritt 3',
  'onboarding.step3.title': 'Erzeuge eine legale Aufstellung',
  'onboarding.step3.description': 'Waehle den Spielmodus, erzeuge eine Aufstellung und nutze Uebernehmen und protokollieren erst dann, wenn Verlauf und Frischetracking aktualisiert werden sollen.',
  'onboarding.step3.action': 'Neues Spiel oeffnen',
  'onboarding.step4.eyebrow': 'Schritt 4',
  'onboarding.step4.title': 'Pruefe deinen Spielverlauf',
  'onboarding.step4.description': 'Der Verlauf zeigt uebernommene Spiele, Ergebnisse und Frische pro Kategorie, damit du vor der naechsten Session sehen kannst, was zuletzt gespielt wurde.',
  'onboarding.step4.action': 'Verlauf oeffnen',
  'onboarding.step5.eyebrow': 'Schritt 5',
  'onboarding.step5.title': 'Schuetze deine Sammlung mit Backup',
  'onboarding.step5.description': 'Nutze Backup, um Sammlung und Verlauf vor riskanten Aenderungen zu exportieren, spaeter einen gespeicherten Stand zu importieren und Ruecksetzungen fuer den Fall bereitzuhalten, dass du bewusst neu beginnen willst.',
  'onboarding.step5.action': 'Backup oeffnen',
  'about.eyebrow': 'Über dieses Projekt',
  'about.title': 'Projektdetails und Entwicklerdiagnosen',
  'about.description': 'Dieser Bereich hält technische Details bereit, ohne sie Spielern aufzudrängen.',
  'about.hide': 'Über ausblenden',
  'about.entries': 'Einträge',
  'modal.cancel': 'Abbrechen',
  'common.heroes': 'Helden',
  'common.masterminds': 'Masterminds',
  'common.villainGroups': 'Schurkengruppen',
  'common.henchmanGroups': 'Handlangergruppen',
  'common.schemes': 'Pläne',
  'common.hero': 'Held',
  'common.heroesLower': 'Helden',
  'common.villainGroup': 'Schurkengruppe',
  'common.henchmanGroup': 'Handlangergruppe',
  'common.scheme': 'Plan',
  'common.wound': 'Wunde',
  'common.wounds': 'Wunden',
  'common.noTeamListed': 'Kein Team angegeben',
  'common.noMandatoryLead': 'Kein Pflicht-Lead',
  'common.mandatoryLead': 'Pflicht-Lead',
  'common.alwaysLeads': 'Führt immer: {name}',
  'collection.group.base': 'Basis',
  'collection.group.large-expansion': 'Große Erweiterungen',
  'collection.group.small-expansion': 'Kleine Erweiterungen',
  'collection.group.standalone': 'Eigenständig',
  'newGame.panel.setupTitle': 'Vorschau der Setup-Engine',
  'newGame.panel.resultTitle': 'Ergebnis der generierten Aufstellung'
};

const JA_MESSAGES = {
  'app.title': 'Legendary: Marvel ランダマイザー',
  'app.subtitle': 'セットを閲覧し、コレクションを管理し、適法なセットアップを生成し、履歴をブラウザー保存で追跡します。',
  'header.locale.label': '言語',
  'header.locale.caption': 'ブラウザー設定に保存',
  'header.theme.label': 'テーマ',
  'tabs.browse.label': '閲覧',
  'tabs.collection.label': 'コレクション',
  'tabs.new-game.label': '新しいゲーム',
  'tabs.history.label': '履歴',
  'tabs.backup.label': 'バックアップ',
  'tabs.new-game.shortLabel': 'ゲーム',
  'browse.hero.eyebrow': 'ようこそ',
  'browse.hero.title': '煩雑さなしで次の Legendary セッションを計画',
  'browse.hero.description': 'すべてのセットを確認し、所持セットを登録し、適法なセットアップを生成し、プレイ履歴を確認できます。',
  'browse.hero.manageCollection': 'コレクション管理',
  'browse.hero.generateGame': 'ゲームを生成',
  'browse.hero.replayWalkthrough': 'ガイドを再表示',
  'browse.hero.aboutProject': 'このプロジェクトについて',
  'browse.panel.title': 'セットを閲覧',
  'browse.panel.description': 'セット名や別名で検索し、種類で絞り込み、内容を展開し、所持状態を直接切り替えます。',
  'browse.visibleSets': '表示中のセット',
  'browse.searchLabel': 'セットを検索',
  'browse.searchPlaceholder': 'セット名または別名で検索',
  'browse.typeFilter': '種類フィルター',
  'browse.emptyFiltered': '現在の検索条件とフィルターに一致するセットはありません。',
  'browse.set.showDetails': '詳細を表示',
  'browse.set.hideDetails': '詳細を隠す',
  'browse.set.inCollection': 'コレクション済み',
  'browse.set.addToCollection': 'コレクションに追加',
  'collection.title': 'マイコレクション',
  'collection.description': 'ここでは閲覧タブやセットアップ生成と同じ保存済みコレクション状態を管理します。',
  'collection.resetSelections': 'すべての選択をリセット',
  'newGame.playerCount': 'プレイヤー数',
  'newGame.playMode': 'プレイモード',
  'newGame.generate': 'セットアップを生成',
  'newGame.regenerate': '再生成',
  'newGame.reroll': '新しいセットアップ',
  'newGame.acceptLog': '確定して記録',
  'history.title': 'ゲーム履歴',
  'history.insights.title': 'インサイト',
  'backup.title': 'バックアップと復元',
  'backup.description': 'コレクション、使用状況、履歴、結果、設定をバージョン付き JSON バックアップとして保存できます。',
  'backup.export': 'バックアップを書き出す',
  'backup.import': 'バックアップを読み込む',
  'onboarding.titleEyebrow': '初回起動ガイド',
  'onboarding.title': '1 分以内でアプリに慣れる',
  'onboarding.previous': '前へ',
  'onboarding.next': '次のステップ',
  'onboarding.finish': 'ガイドを完了',
  'onboarding.skip': '今はスキップ',
  'onboarding.stepPrefix': 'ステップ {current} / {total}',
  'onboarding.step1.eyebrow': 'ステップ 1',
  'onboarding.step1.title': 'まずは全カタログを確認',
  'onboarding.step1.description': 'セット名や別名で検索し、商品タイプで絞り込み、カードを展開してヒーロー、マスターマインド、ヴィラン・グループ、ヘンチマン・グループ、策略を確認できます。',
  'onboarding.step1.action': '閲覧にとどまる',
  'onboarding.step2.eyebrow': 'ステップ 2',
  'onboarding.step2.title': '実際に持っているものを記録',
  'onboarding.step2.description': '閲覧またはコレクションで所持セットを切り替え、セットアップ生成の前にコレクション数とプレイヤー人数での実行可能性を確認します。',
  'onboarding.step2.action': 'コレクションを開く',
  'onboarding.step3.eyebrow': 'ステップ 3',
  'onboarding.step3.title': '適法なセットアップを生成',
  'onboarding.step3.description': 'プレイモードを選び、セットアップを生成し、履歴と新鮮度の追跡を更新したいときだけ確定して記録を使います。',
  'onboarding.step3.action': '新しいゲームを開く',
  'onboarding.step4.eyebrow': 'ステップ 4',
  'onboarding.step4.title': 'プレイ履歴を確認',
  'onboarding.step4.description': '履歴では受け入れたゲーム、結果、カテゴリごとの新鮮度を確認できるため、次のセッション前に最近遊んだ内容を把握できます。',
  'onboarding.step4.action': '履歴を開く',
  'onboarding.step5.eyebrow': 'ステップ 5',
  'onboarding.step5.title': 'バックアップでコレクションを守る',
  'onboarding.step5.description': 'バックアップでは、危険な変更の前にコレクションと履歴を書き出し、あとで保存済みスナップショットを読み込み、最初からやり直したいときのためにリセット操作も使えます。',
  'onboarding.step5.action': 'バックアップを開く',
  'about.eyebrow': 'このプロジェクトについて',
  'about.title': 'プロジェクト詳細と開発診断',
  'about.description': 'このセクションでは、プレイヤー向け UI から切り離して技術情報を確認できます。',
  'about.hide': '非表示',
  'about.entries': '件',
  'modal.cancel': 'キャンセル',
  'common.heroes': 'ヒーロー',
  'common.masterminds': 'マスターマインド',
  'common.villainGroups': 'ヴィラン・グループ',
  'common.henchmanGroups': 'ヘンチマン・グループ',
  'common.schemes': '策略',
  'common.hero': 'ヒーロー',
  'common.heroesLower': 'ヒーロー',
  'common.villainGroup': 'ヴィラン・グループ',
  'common.henchmanGroup': 'ヘンチマン・グループ',
  'common.scheme': '策略',
  'common.wound': '傷',
  'common.wounds': '傷',
  'common.noTeamListed': 'チーム表記なし',
  'common.noMandatoryLead': '必須リードなし',
  'common.mandatoryLead': '必須リード',
  'common.alwaysLeads': '常にリード: {name}',
  'collection.group.base': '基本セット',
  'collection.group.large-expansion': '大型拡張',
  'collection.group.small-expansion': '小型拡張',
  'collection.group.standalone': '単独版',
  'newGame.panel.setupTitle': 'セットアップエンジンのプレビュー',
  'newGame.panel.resultTitle': '生成されたセットアップ結果'
};

const KO_MESSAGES = {
  'app.title': 'Legendary: Marvel 랜덤라이저',
  'app.subtitle': '세트를 둘러보고, 컬렉션을 관리하고, 합법적인 세팅을 생성하고, 브라우저 저장으로 기록을 추적합니다.',
  'header.locale.label': '언어',
  'header.locale.caption': '브라우저 환경설정에 저장됨',
  'header.theme.label': '테마',
  'tabs.browse.label': '둘러보기',
  'tabs.collection.label': '컬렉션',
  'tabs.new-game.label': '새 게임',
  'tabs.history.label': '기록',
  'tabs.backup.label': '백업',
  'browse.hero.eyebrow': '환영합니다',
  'browse.hero.title': '복잡함 없이 다음 Legendary 세션 계획하기',
  'browse.hero.description': '모든 세트를 살펴보고, 보유 컬렉션을 표시하고, 합법적인 세팅을 생성하고, 플레이 기록을 검토하세요.',
  'browse.hero.manageCollection': '컬렉션 관리',
  'browse.hero.generateGame': '게임 생성',
  'browse.hero.replayWalkthrough': '안내 다시 보기',
  'browse.hero.aboutProject': '프로젝트 정보',
  'browse.panel.title': '세트 둘러보기',
  'browse.panel.description': '세트 이름이나 별칭으로 검색하고, 제품 유형으로 필터링하고, 카드 내용을 펼치고, 보유 여부를 바로 바꿀 수 있습니다.',
  'browse.visibleSets': '표시된 세트',
  'browse.searchLabel': '세트 검색',
  'browse.searchPlaceholder': '세트 이름 또는 별칭으로 검색',
  'browse.typeFilter': '유형 필터',
  'browse.emptyFiltered': '현재 검색과 필터에 맞는 세트가 없습니다.',
  'browse.set.showDetails': '세부 정보 보기',
  'browse.set.hideDetails': '세부 정보 숨기기',
  'browse.set.inCollection': '컬렉션에 있음',
  'browse.set.addToCollection': '컬렉션에 추가',
  'collection.title': '내 컬렉션',
  'collection.description': '여기서 둘러보기와 세팅 생성에 쓰이는 동일한 저장 상태로 보유 세트를 관리합니다.',
  'collection.resetSelections': '모든 선택 초기화',
  'newGame.playerCount': '플레이어 수',
  'newGame.playMode': '플레이 모드',
  'newGame.generate': '세팅 생성',
  'newGame.regenerate': '다시 생성',
  'newGame.reroll': '새 세팅',
  'newGame.acceptLog': '확정 및 기록',
  'history.title': '게임 기록',
  'history.insights.title': '인사이트',
  'backup.title': '백업 및 복원',
  'backup.description': '컬렉션, 사용 통계, 기록, 결과, 환경설정을 버전이 있는 JSON 백업으로 내보내고 다시 가져올 수 있습니다.',
  'backup.export': '백업 내보내기',
  'backup.import': '백업 가져오기',
  'onboarding.titleEyebrow': '첫 실행 안내',
  'onboarding.title': '1분 안에 앱 익히기',
  'onboarding.previous': '이전',
  'onboarding.next': '다음 단계',
  'onboarding.finish': '안내 완료',
  'onboarding.skip': '지금은 건너뛰기',
  'onboarding.stepPrefix': '{total}단계 중 {current}단계',
  'onboarding.step1.eyebrow': '1단계',
  'onboarding.step1.title': '먼저 전체 카탈로그 둘러보기',
  'onboarding.step1.description': '세트 이름이나 별칭으로 검색하고, 제품 유형으로 필터링하고, 카드를 펼쳐 히어로, 마스터마인드, 빌런 그룹, 핸치맨 그룹, 계획을 확인하세요.',
  'onboarding.step1.action': '둘러보기에 머무르기',
  'onboarding.step2.eyebrow': '2단계',
  'onboarding.step2.title': '실제로 가진 세트 표시하기',
  'onboarding.step2.description': '둘러보기나 컬렉션에서 보유 세트를 전환한 다음, 세팅을 생성하기 전에 컬렉션 합계와 플레이어 수 기준 가능 여부를 확인하세요.',
  'onboarding.step2.action': '컬렉션 열기',
  'onboarding.step3.eyebrow': '3단계',
  'onboarding.step3.title': '합법적인 세팅 생성하기',
  'onboarding.step3.description': '플레이 모드를 선택하고 세팅을 생성한 뒤, 기록과 신선도 추적을 업데이트하려는 경우에만 확정 및 기록을 사용하세요.',
  'onboarding.step3.action': '새 게임 열기',
  'onboarding.step4.eyebrow': '4단계',
  'onboarding.step4.title': '플레이 기록 확인하기',
  'onboarding.step4.description': '기록에서는 확정된 게임, 결과, 카테고리별 신선도를 보여 주어 다음 세션 전에 최근에 무엇을 했는지 확인할 수 있습니다.',
  'onboarding.step4.action': '기록 열기',
  'onboarding.step5.eyebrow': '5단계',
  'onboarding.step5.title': '백업으로 컬렉션 보호하기',
  'onboarding.step5.description': '백업 탭에서 위험한 변경 전에 컬렉션과 기록을 내보내고, 나중에 저장한 스냅샷을 다시 가져오고, 정말 처음부터 다시 시작하고 싶을 때만 초기화를 사용할 수 있습니다.',
  'onboarding.step5.action': '백업 열기',
  'about.eyebrow': '프로젝트 정보',
  'about.title': '프로젝트 세부사항 및 개발 진단',
  'about.description': '이 섹션은 플레이어용 화면과 분리해서 구현 관련 정보를 보여줍니다.',
  'about.hide': '숨기기',
  'about.entries': '개',
  'modal.cancel': '취소',
  'common.heroes': '히어로',
  'common.masterminds': '마스터마인드',
  'common.villainGroups': '빌런 그룹',
  'common.henchmanGroups': '핸치맨 그룹',
  'common.schemes': '계획',
  'common.hero': '히어로',
  'common.heroesLower': '히어로',
  'common.villainGroup': '빌런 그룹',
  'common.henchmanGroup': '핸치맨 그룹',
  'common.scheme': '계획',
  'common.wound': '상처',
  'common.wounds': '상처',
  'common.noTeamListed': '표시된 팀 없음',
  'common.noMandatoryLead': '필수 리드 없음',
  'common.mandatoryLead': '필수 리드',
  'common.alwaysLeads': '항상 리드: {name}',
  'collection.group.base': '기본',
  'collection.group.large-expansion': '대형 확장',
  'collection.group.small-expansion': '소형 확장',
  'collection.group.standalone': '독립형',
  'newGame.panel.setupTitle': '세팅 엔진 미리보기',
  'newGame.panel.resultTitle': '생성된 세팅 결과'
};

const ES_MESSAGES = {
  'app.title': 'Aleatorizador de Legendary: Marvel',
  'app.subtitle': 'Explora expansiones, gestiona tu colección, genera configuraciones legales y sigue el historial con persistencia en el navegador.',
  'header.locale.label': 'Idioma',
  'header.locale.caption': 'Guardado en las preferencias del navegador',
  'header.theme.label': 'Tema',
  'tabs.browse.label': 'Explorar',
  'tabs.collection.label': 'Colección',
  'tabs.new-game.label': 'Nueva partida',
  'tabs.history.label': 'Historial',
  'tabs.backup.label': 'Copia',
  'browse.hero.eyebrow': 'Bienvenido',
  'browse.hero.title': 'Planifica la próxima sesión de Legendary sin desorden',
  'browse.hero.description': 'Explora todas las expansiones, marca tu colección, genera una configuración legal y revisa el historial de juego desde una sola app estática.',
  'browse.hero.manageCollection': 'Gestionar colección',
  'browse.hero.generateGame': 'Generar partida',
  'browse.hero.replayWalkthrough': 'Repetir guía',
  'browse.hero.aboutProject': 'Sobre este proyecto',
  'browse.panel.title': 'Explorar expansiones',
  'browse.panel.description': 'Busca por nombre o alias, filtra por tipo de producto, expande una carta para ver su contenido y cambia la propiedad directamente.',
  'browse.visibleSets': 'Expansiones visibles',
  'browse.searchLabel': 'Buscar expansiones',
  'browse.searchPlaceholder': 'Buscar por nombre o alias',
  'browse.typeFilter': 'Filtro de tipo',
  'browse.emptyFiltered': 'Ninguna expansión coincide con la búsqueda y el filtro actuales.',
  'browse.set.showDetails': 'Mostrar detalles',
  'browse.set.hideDetails': 'Ocultar detalles',
  'browse.set.inCollection': 'En la colección',
  'browse.set.addToCollection': 'Añadir a la colección',
  'collection.title': 'Mi colección',
  'collection.description': 'Gestiona aquí las expansiones que tienes con el mismo estado persistente usado por Explorar y la generación.',
  'collection.resetSelections': 'Restablecer todas las selecciones',
  'newGame.playerCount': 'Número de jugadores',
  'newGame.playMode': 'Modo de juego',
  'newGame.generate': 'Generar configuración',
  'newGame.regenerate': 'Regenerar',
  'newGame.reroll': 'Nueva configuración',
  'newGame.acceptLog': 'Aceptar y registrar',
  'history.title': 'Historial de partidas',
  'history.insights.title': 'Panel de análisis',
  'backup.title': 'Copia y restauración',
  'backup.description': 'Exporta tu colección, uso, historial, resultados y preferencias a una copia JSON con versión. Más tarde puedes importarla y mezclarla o reemplazar los datos locales.',
  'backup.export': 'Exportar copia',
  'backup.import': 'Importar copia',
  'onboarding.titleEyebrow': 'Guia de primer uso',
  'onboarding.title': 'Domina la app en menos de un minuto',
  'onboarding.previous': 'Anterior',
  'onboarding.next': 'Siguiente paso',
  'onboarding.finish': 'Terminar guía',
  'onboarding.skip': 'Omitir por ahora',
  'onboarding.stepPrefix': 'Paso {current} de {total}',
  'onboarding.step1.eyebrow': 'Paso 1',
  'onboarding.step1.title': 'Explora primero el catálogo completo',
  'onboarding.step1.description': 'Busca por nombre de expansión o alias, filtra por tipo de producto y despliega cartas para revisar héroes, mentes maestras, grupos de villanos, grupos de secuaces y planes.',
  'onboarding.step1.action': 'Seguir en Explorar',
  'onboarding.step2.eyebrow': 'Paso 2',
  'onboarding.step2.title': 'Marca lo que realmente tienes',
  'onboarding.step2.description': 'Usa Explorar o Colección para alternar las expansiones que posees y luego confirma los totales de tu colección y la viabilidad según el número de jugadores antes de generar configuraciones.',
  'onboarding.step2.action': 'Abrir Colección',
  'onboarding.step3.eyebrow': 'Paso 3',
  'onboarding.step3.title': 'Genera una configuración legal',
  'onboarding.step3.description': 'Elige el modo de juego, genera una configuración y usa Aceptar y registrar solo cuando quieras actualizar el historial y el seguimiento de frescura.',
  'onboarding.step3.action': 'Abrir Nueva partida',
  'onboarding.step4.eyebrow': 'Paso 4',
  'onboarding.step4.title': 'Revisa tu historial de partidas',
  'onboarding.step4.description': 'El historial muestra las partidas aceptadas, los resultados y la frescura por categoría para que veas lo que jugaste recientemente antes de la siguiente sesión.',
  'onboarding.step4.action': 'Abrir Historial',
  'onboarding.step5.eyebrow': 'Paso 5',
  'onboarding.step5.title': 'Protege tu colección con Copia',
  'onboarding.step5.description': 'Usa Copia para exportar tu colección y tu historial antes de cambios arriesgados, volver a importar una instantánea guardada más tarde y dejar los reinicios para cuando de verdad quieras empezar de cero.',
  'onboarding.step5.action': 'Abrir Copia',
  'about.eyebrow': 'Sobre este proyecto',
  'about.title': 'Detalles del proyecto y diagnósticos de desarrollo',
  'about.description': 'Esta sección mantiene disponibles los detalles técnicos sin ponerlos delante de los jugadores.',
  'about.hide': 'Ocultar información',
  'about.entries': 'entradas',
  'modal.cancel': 'Cancelar',
  'common.heroes': 'Héroes',
  'common.masterminds': 'Mentes maestras',
  'common.villainGroups': 'Grupos de villanos',
  'common.henchmanGroups': 'Grupos de secuaces',
  'common.schemes': 'Planes',
  'common.hero': 'héroe',
  'common.heroesLower': 'héroes',
  'common.villainGroup': 'grupo de villanos',
  'common.henchmanGroup': 'grupo de secuaces',
  'common.scheme': 'plan',
  'common.wound': 'Herida',
  'common.wounds': 'Heridas',
  'common.noTeamListed': 'Sin equipo indicado',
  'common.noMandatoryLead': 'Sin líder obligatorio',
  'common.mandatoryLead': 'Líder obligatorio',
  'common.alwaysLeads': 'Siempre lidera: {name}',
  'collection.group.base': 'Base',
  'collection.group.large-expansion': 'Expansiones grandes',
  'collection.group.small-expansion': 'Expansiones pequeñas',
  'collection.group.standalone': 'Independiente',
  'newGame.panel.setupTitle': 'Vista previa del motor de configuración',
  'newGame.panel.resultTitle': 'Resultado de la configuración generada'
};

const LOCALE_OPTIONS = [...SELECTABLE_LOCALES];
const LOCALE_IDS = new Set(LOCALE_OPTIONS.map((locale) => locale.id));

function interpolate(template, params) {
  return String(template).replaceAll(/\{([^}]+)\}/g, (_, key) => {
    const value = params?.[key];
    return value === undefined || value === null ? '' : String(value);
  });
}

function getMessagesForLocale(localeId) {
  if (localeId === 'fr-FR') {
    return { ...EN_MESSAGES, ...FR_MESSAGES };
  }

  if (localeId === 'de-DE') {
    return { ...EN_MESSAGES, ...DE_MESSAGES };
  }

  if (localeId === 'ja-JP') {
    return { ...EN_MESSAGES, ...JA_MESSAGES };
  }

  if (localeId === 'ko-KR') {
    return { ...EN_MESSAGES, ...KO_MESSAGES };
  }

  if (localeId === 'es-ES') {
    return { ...EN_MESSAGES, ...ES_MESSAGES };
  }

  return EN_MESSAGES;
}

function collectFallbackKeys(_localeId) {
  return [];
}

export function normalizeLocaleId(localeId) {
  return LOCALE_IDS.has(localeId) ? localeId : DEFAULT_LOCALE_ID;
}

export function getSelectableLocales() {
  return [...SELECTABLE_LOCALES];
}

export function getLocaleOption(localeId) {
  return LOCALE_OPTIONS.find((locale) => locale.id === normalizeLocaleId(localeId)) || SELECTABLE_LOCALES[0];
}

function titleCaseWords(value) {
  return String(value)
    .split('-')
    .map((segment) => segment ? segment[0].toUpperCase() + segment.slice(1) : segment)
    .join(' ');
}

export function createLocaleTools(localeId) {
  const normalizedLocaleId = normalizeLocaleId(localeId);
  const messages = getMessagesForLocale(normalizedLocaleId);
  const fallbackKeys = collectFallbackKeys(normalizedLocaleId);
  const option = getLocaleOption(normalizedLocaleId);
  const numberFormatter = new Intl.NumberFormat(normalizedLocaleId);
  const dateFormatter = new Intl.DateTimeFormat(normalizedLocaleId, { dateStyle: 'medium' });
  const dateTimeFormatter = new Intl.DateTimeFormat(normalizedLocaleId, { dateStyle: 'medium', timeStyle: 'short' });
  const listFormatter = new Intl.ListFormat(normalizedLocaleId, { style: 'long', type: 'conjunction' });

  const t = (key, params = {}) => interpolate(messages[key] ?? EN_MESSAGES[key] ?? key, params);

  return {
    localeId: normalizedLocaleId,
    documentLang: normalizedLocaleId,
    localeLabel: option.nativeLabel,
    fallbackKeys,
    hasFallbacks: fallbackKeys.length > 0,
    t,
    formatNumber(value, fallback = '—') {
      if (value === null || value === undefined || value === '') {
        return fallback;
      }
      return numberFormatter.format(value);
    },
    formatDate(value, fallback = '—') {
      if (!value) {
        return fallback;
      }
      return dateFormatter.format(new Date(value));
    },
    formatDateTime(value, fallback = '—') {
      if (!value) {
        return fallback;
      }
      return dateTimeFormatter.format(new Date(value));
    },
    formatList(values, fallback = '') {
      return Array.isArray(values) && values.length ? listFormatter.format(values) : fallback;
    },
    formatPlayerLabel(count) {
      return count === 1 ? t('common.player', { count: numberFormatter.format(count) }) : t('common.players', { count: numberFormatter.format(count) });
    },
    formatGameCount(count) {
      return `${numberFormatter.format(count)} ${count === 1 ? t('common.game') : t('common.games')}`;
    },
    formatPlayCount(count) {
      return t('history.insights.playCount', {
        count: numberFormatter.format(count),
        playWord: count === 1 ? t('common.play') : t('common.plays')
      });
    },
    formatEntityCount(count, singularKey, pluralKey = singularKey) {
      const noun = count === 1 ? t(singularKey) : t(pluralKey);
      return `${numberFormatter.format(count)} ${noun}`;
    },
    getTabLabel(tabId) {
      return t(`tabs.${tabId}.label`);
    },
    getTabShortLabel(tabId) {
      return t(`tabs.${tabId}.shortLabel`);
    },
    getTabDescription(tabId) {
      return t(`tabs.${tabId}.description`);
    },
    getThemeLabel(themeId) {
      return t(`theme.${themeId}.label`);
    },
    getThemeDescription(themeId) {
      return t(`theme.${themeId}.description`);
    },
    getHistoryGroupingLabel(modeId) {
      return t(`history.group.${modeId}`);
    },
    getUsageLabel(category) {
      return t(`common.${category}`);
    },
    getOutcomeLabel(outcomeId) {
      return t(`common.outcome.${outcomeId}`);
    },
    formatResultStatus(result) {
      if (result?.status !== 'completed') {
        return t('common.pendingResult');
      }
      const outcomeLabel = this.getOutcomeLabel(result.outcome) || t('common.unknown');
      return result.score === null
        ? outcomeLabel
        : `${outcomeLabel} · ${t('common.score', { score: numberFormatter.format(result.score) })}`;
    },
    getPlayModeLabel(playMode, playerCount = 1) {
      if (playMode === 'advanced-solo') {
        return t('common.playMode.advanced-solo');
      }
      if (playMode === 'two-handed-solo') {
        return t('common.playMode.two-handed-solo');
      }
      return Number(playerCount) === 1 ? t('common.playMode.standardSolo') : t('common.playMode.standard');
    },
    getPlayModeDescription(playMode, playerCount = 1) {
      if (playMode === 'advanced-solo') {
        return t('common.playMode.advanced-soloDescription');
      }
      if (playMode === 'two-handed-solo') {
        return t('common.playMode.two-handed-soloDescription');
      }
      return Number(playerCount) === 1 ? t('common.playMode.standardSoloDescription') : t('common.playMode.standardDescription');
    },
    getPlayModeHelpText(playerCount, playMode) {
      if (Number(playerCount) !== 1) {
        return t('common.playMode.multiplayerDisabled');
      }
      if (playMode === 'two-handed-solo') {
        return t('common.playMode.twoHandedHelp');
      }
      return t('common.playMode.chooseSolo');
    },
    formatPersistedPlayMode(playerCount, playMode) {
      return t('common.format.persistedPlayMode', {
        players: numberFormatter.format(playerCount),
        mode: this.getPlayModeLabel(playMode, playerCount)
      });
    },
    getBrowseTypeLabel(type) {
      return t(`browse.typeLabel.${type}`);
    },
    getBrowseTypeFilterLabel(type) {
      return t(`browse.type.${type}`);
    },
    getCollectionGroupLabel(type) {
      return t(`collection.group.${type}`);
    },
    getToastVariantLabel(variant) {
      return t(`toast.variant.${variant}`);
    },
    localizeNotice(notice) {
      if (notice === 'Recovered invalid preference values during state hydration.') {
        return t('persistence.invalidPrefs');
      }
      return notice;
    },
    localizeValidationMessage(message) {
      if (message === 'Choose Win or Loss before saving the result.') {
        return t('validation.chooseOutcome');
      }
      if (message === 'Enter a score before saving the result.') {
        return t('validation.enterWinScore');
      }
      if (message === 'Score must be a whole number that is 0 or greater.') {
        return t('validation.scoreWholeNumber');
      }
      return message;
    },
    formatGroupingModeLabel(modeId) {
      return modeId === 'none' ? t('history.group.none') : titleCaseWords(this.getHistoryGroupingLabel(modeId));
    }
  };
}